Repository UniversityOfDundee-Computing/cw2-web-application-development-project-alliance, pull requests merged in 2025-05, with the labels that each got.

#56 README documentation, Meeting Notes, and Footer integration
  Materials/footer/footer.css
  README.md
  fav.html
  index.html
  index.js
  meeting/meeting1.txt
  meeting/meeting2.txt
  meeting/meeting3.txt
  movies.css
  movies.html
  movies.js
  welcome.html
  welcome.js
Labels: bug, documentation, enhancement

#58 removed trailing slashes and improved <img> tags
  README.md
  fav.html
  movies.html
Labels: bug

#59 Added Application-Idea and Video link
  README.md
  meeting/application-idea.pdf
Labels: documentation, enhancement
